resolver: lts-22.41

packages:
- .

extra-deps:
  - postgresql-binary-0.12.4.2 
  - postgresql-libpq-0.9.4.3
  - hasql-1.5.0.2 
  - opaleye-0.9.2.0 
  - product-profunctors-0.11.0.3 
  - uuid-1.3.15
  - rel8-1.3.1.0

allow-newer: true