GET http://localhost:3000/api/wanaka/token/validate HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NDExNzg1MDEsInVzZXIiOiJhcGktZGV2In0.K7zHg8b5TaB-x2nalAmFA_saFqsHt2c-nLTGVgTMj2s
x-client-id: wanaka-budget