GET http://localhost:3000/api/wanaka/token/validate HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NDE3OTM5NTcsInVzZXIiOiJhcGktZGV2In0.SXYNektEvgGRdVsMOf84-gcWe5sqPgaP4jCgiAkOn-I
x-client-id: wanaka-budget